<a href="https://colab.research.google.com/github/crew-guy/ml-with-tensorflow/blob/main/intoduction-to-tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover some of the most fundamental concepts of tensors using TensorFlow

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up Python functions)
* Using GPUs with tensorflow (or TPUs)

## Introduction to tensors

In [1]:
# Import tensorflow

import tensorflow as tf
print(tf.__version__)


2.9.2


In [3]:
 # Create a tensor from a tensor like object
 scalar = tf.constant(7)
 print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [5]:
# Check the number of dimensions of a tensor
print(scalar.ndim)  

0


In [6]:
# Create a vector
vector = tf.constant([10,10])
print(vector)

tf.Tensor([10 10], shape=(2,), dtype=int32)


In [9]:
# Create a matrix
matrix = tf.constant([[1,2],[3,4]])
    print(matrix, matrix.ndim)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 2


In [12]:
# Specify the data type with the dtype parameter
matrix2 = tf.constant([
    [1.,2.],
    [3.,4.],
    [5.,6.]
    ], dtype = tf.float16)
print(matrix2, matrix2.ndim)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16) 2


 ## What we've created so far
Scalar: A constant number
<br/>
Vector: A array of numbers representing a magnitude with a direction (eg: wind speed)
<br/>
Matrix: A 2-D array of numbers
<br/>
Tensor: An n-dimensional array of numbers


## Creating tensors withh `tf.Variable`

In [14]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Values inside a changeable_tensor (created with tf.Variable) can be reassigned whereas the same cannot be done for unchangeable_tensor

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

🔑 Note : Rarely in practice, we decide, whether to use tf.constant() or tf.Variable, as Tensorflow does this for use. However, if in doubt, use tf.constant and change it later

## Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers



In [16]:
# Create 2 random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [17]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## Shuffle the order of elements in a tensor

Valuable when you want to shuffle your data so that inherent order does not affect learning

In [20]:
# Shuffling a tensor
not_shuffled = tf.Variable([[10,7],[6,5],[3,2]])

# Using random shuffle - shuffling happens along the outermost dimension, i.e. dimension-0
shuffled = tf.random.shuffle(not_shuffled)

shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  2],
       [10,  7],
       [ 6,  5]], dtype=int32)>

In [25]:
# Setting a seed for shuffling will allow reproducibity - https://www.tensorflow.org/api_docs/python/tf/random/set_seed


# Setting "global seed"
tf.random.set_seed(22)


# Setting operation-level aka "local seed"
# Local seeds override global seeds
tf.random.shuffle(not_shuffled, seed= 21)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  5],
       [10,  7],
       [ 3,  2]], dtype=int32)>